config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :posts do
    resource :like, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  mount_uploader :image, ImageUploader #carrierwave追加
  attr_accessor :remember_token

  def self.search(search)
    if search
      where(['title LIKE ?', "%#{search}%"]) #検索とuseanameの部分一致を表示。
    else
      Post.all #全て表示させる
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader #carrierwave追加
  attr_accessor :remember_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts, dependent: :destroy
         has_many :likes, dependent: :destroy
         has_many :comments, dependent: :destroy

  def self.search(search)
    if search
      where(['username LIKE ?', "%#{search}%"]) #検索とuseanameの部分一致を表示。
    else
      User.all #全て表示させる
    end
  end

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @comment = Comment.find(params[:post_id])
    if @comment.destroy
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :post_id, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = current_user.likes.find_by(post_id: @post.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.search(params[:search])
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post), notice: '投稿に成功しました。'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path, alert: '不正なアクセスです。'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: '更新に成功しました。'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(post.user), notice: "レシピを削除しました。"
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :image, :comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.search(params[:search])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  private  #privateの下にあるアクションはusercontrollerないでしか呼び出せない  データがコントローラーないでしか呼び出せないのでセキュリティ良
  def user_params
    params.require(:user).permit(:username, :email, :profile, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="section home-index_title">
  <article class="media home-index_title">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="title is-size-1" style="font-family: cursive;">RecoGour</strong>
        </p>
        <p>
        RecoGourで、あなたのオススメの料理やお店を投稿しよう
        </p>
      </div>
      <div class="columns is-centered">
        <div class="column is-3">
          <br>
          <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-fullwidth" %>
          <br>
          <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-fullwidth" %>
        </div>
      </div>
    </div>
  </article>
  <br>
  <div class="columns is-centered">
    <div class="column">
      <figure>
        <div class="main-image"></div>
      </figure>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recogour</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.16/vue.min.js"></script>
  </head>

  <body>

  <div class="home-index_flash">
    <% if flash[:notice] %>
      <div class="notification is-info home-index_alert">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger home-index_alert">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
  </div>

  <div id="app">
    <nav class="navbar is-light is-fixed-top" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: cursive;">RecoGour</h1>
        <% end %>
        <div class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample" @click="isOpen = !isOpen" v-bind:class="{'is-active': isOpen}">
          <span aria-hidden = "true"></span>
          <span aria-hidden = "true"></span>
          <span aria-hidden = "true"></span>
        </div>
      </div>

    <% if user_signed_in? %>
        <div id="navbarBasicExample" class="navbar-menu" v-bind:class="{'is-active': isOpen}">
          <div class="navbar-start">
            <div class="navbar-item home-index_icon">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to posts_path do %>
                    <i class="fas fa-book-reader fa-2x"></i> <%# 投稿一覧 %>
                  <% end %>
                </p>
                <p class="control">
                  <%= link_to new_post_path do %>
                    <i class="far fa-edit fa-2x"></i> <%# 新規投稿 %>
                  <% end %>
                </p>
                <p class="control">
                    <%= link_to users_path do %>
                      <i class="fas fa-address-book fa-2x"></i> <%# アカウント一覧 %>
                    <% end %>
                </p>
                <p class="control">
                  <%= link_to user_path(current_user) do %>
                    <i class="fas fa-home fa-2x"></i> <%# マイページ %>
                  <% end %>
                </p>
                <p class="control">
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fas fa-sign-out-alt fa-2x"></i> <%# ログアウト %>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div id="navbarExampleTransparentExample" class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
                <p class="control">
                  <%= link_to users_path do %>
                    <i class="fas fa-address-book fa-2x"></i> <%# アカウント一覧 %>
                  <% end %>
                </p>
                <p class="control">
                  <%= link_to new_user_session_path do %>
                    <i class="fas fa-sign-in-alt fa-2x"></i> <%# ログイン %>
                  <% end %>
                </p>
                <p class="control">
                  <%= link_to new_user_registration_path do %>
                    <i class="far fa-plus-square fa-2x"></i> <%# 新規登録 %>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </nav>
    </div>

  <script>
    var app = new Vue({
        el: '#app',
        data: {
            isOpen: false
        }
    })
  </script>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%# <section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        投稿編集
      </h1>
    </div>
  </div>
</section> %>

<% if @post.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model:@post do |f| %>
          <div class="field">
            <%= f.label :title, "投稿名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "内容", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.file_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/index.html.erb
<%# <section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        投稿一覧
      </h1>
    </div>
  </div>
</section> %>

<%# 検索フォーム %>
<section>
  <%= form_tag(posts_path, :method => "get") do %>
    <p class="media">
      <%= text_field_tag :search, params[:search], class: "form column is-3" %>
      <%= submit_tag "検索", :title => nil ,class: "user-btn button is-info" %>
    </p>
  <% end %>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @posts.each do |post| %>
        <div class="column is-3">
          <div class="card">
            <div class="media postindex">
              <div class="media-left">
                <figure class="image is-48x48">
                  <%= image_tag post.user.image.url if post.user.image.present? %>
                </figure>
              </div>
              <div class="media-content post-username">
                <div class="title"><%= link_to post.user.username, user_path(post.user) %></div>
              </div>
            </div>
            <div class="card-image">
              <figure class="image is-4by3"> <%# 投稿の画像を表示 %>
                <%= link_to post_path(post) do %>
                  <%= image_tag post.image.url if post.image.present? %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="content">
                <% if current_user.already_liked?(post) %>
                  <%= link_to post_like_path(post), method: :delete do %>
                    <i class="fas fa-heart"></i>
                  <% end %>
                <% else %>
                  <%= link_to post_like_path(post), method: :post do %>
                    <i class="far fa-heart"></i>
                  <% end %>
                <% end %>
                <%# <%= post.likes.count %> <%# カウント表示させる場合 %>
                <%# <i class="far fa-comment"></i> %>
              </div>
              <h2 class="post_title"><%= link_to post.title, post_path(post) %></h2>
                <time><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<%# <section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規投稿作成
      </h1>
    </div>
  </div>
</section> %>

<% if @post.errors.any? %> <%# エラー時にメッセージを表示させる%>
  <div class="notification is-danger">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered home-index_container">
      <div class="column is-6">
        <%= form_with model:@post do |f| %>
          <div class="field">
            <%= f.label :title, "投稿名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "投稿内容", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.file_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<%# <section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        投稿詳細
      </h1>
    </div>
  </div>
</section> %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
      <%# <div class="column is-7"> %>
        <%# <article class="panel is-link"> %>
          <%# <p class="panel-heading"> %>
            <%# By <%= @post.user.username %>
          <%# </p> %>
          <%# <div class="panel-block"> %>
            <%# <p class="control">
              <%= @post.user.profile %>
            <%# </p> %>
          <%# </div> %>
          <%= link_to user_path(@post.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user fa-lg" aria-hidden="true"></i>
            </span>
            <div class="user-name">
             <%= @post.user.username %>
            </div>
          <% end %>
        <%# </article> %>
      <%# </div> %>
          <div class="card-image">
            <figure class="image is-4by3">
              <%= image_tag @post.image.url if @post.image.present? %>
            </figure>
          </div>
          <div class="card-content">
              <div class="media">
                <% if current_user.already_liked?(@post) %>
                  <%= link_to post_like_path(@post), method: :delete do %>
                    <i class="fas fa-heart"></i>
                  <% end %>
                <% else %>
                  <%= link_to post_like_path(@post), method: :post do %>
                    <i class="far fa-heart unlike-btn"></i>
                  <% end %>
                <% end %>
                <%# <%= @post.likes.count %> <%#カウント表示させる場合 %>
              </div>
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @post.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>投稿内容</th>
                </tr>
                <tr>
                  <td><%= simple_format @post.body %></td>
                </tr>
              </table>
              <% if @post.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_post_path(@post), class: "button is-success" %>
              <% end %>
            </div>
              <table class="table is-narrow">
                <tr>
                  <th  >コメント一覧</th>
                </tr>
                <tr class="comment_content">
                  <td class="comment">
                    <% @comments.each do |comment| %>
                      <%= link_to comment.user.username, user_path(comment.user_id), class: "comment_username" %>
                        <%= comment.body %>
                        <% if comment.user_id == current_user.id %>
                          <%=link_to post_comments_path(comment.id), method: :delete do %>
                            <i class="far fa-trash-alt"></i>
                          <% end %>
                        <% end %>
                        <hr>
                    <% end %>
                  </td>
                </tr>
              </table>
              <%= form_with model:[@post, @comment] do |f| %>
                <%= f.text_field :body, class: "input" %>
                <br>
                <%= f.submit 'コメントする', class: "button is-success sendbtn" %>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<%# <section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section> %>

<% if @user.errors.any? %> <%# エラー時にメッセージを表示させる%>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model:@user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "プロフィール画像", class: "label" %>
            <%= f.file_field :image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<%# <section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        アカウント一覧
      </h1>
    </div>
  </div>
</section> %>

<section>
  <%= form_tag(users_path, :method => "get") do %>
    <p class="media">
      <%= text_field_tag :search, params[:search], class: "form column is-3" %>
      <%= submit_tag "検索", :name => nil ,class: "user-btn button is-info" %>
    </p>
  <% end %>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image is-128x128">
                  <%= link_to user_path(user) do %>
                    <%= image_tag user.image.url if user.image.present? %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数：<%= user.posts.count %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
  
<%# <section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title"> %>
         <%# <%= @user.username %>
      <%# </h1>
    </div>
  </div>
</section> %>

<section class="section">
  <div class="container">
    <div class="columns is-centered home-index_container">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= image_tag @user.image.url if @user.image.present? %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %> <%#カレントユーザーでログイン中の人の情報をとってくる%>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.posts.each do |post| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to post_path(post) do %>
                  <%= image_tag post.image.url if post.image.present? %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to post_path(post), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    この投稿を見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_post_path(post), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      この投稿を編集する
                    <% end %>
                    <%= link_to post_path(post), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      この投稿を削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>